/**
 *
 * NumericalChameleon 3.0.0 - more than an unit converter - a NumericalChameleon
 * Copyright (c) 2001-2020 Dipl.-Inf. (FH) Johann Nepomuk Loefflmann, All Rights
 * Reserved, <http://www.numericalchameleon.net>.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package net.numericalchameleon.gui.dialogs.listgenerator;

import net.numericalchameleon.util.calendarlistformats.VCalendarListFormat;
import net.numericalchameleon.util.calendarlistformats.XCalendarListFormat;
import net.numericalchameleon.util.calendarlistformats.ICalendarListFormat;
import net.numericalchameleon.util.calendarlistformats.OutlookListFormat;
import net.numericalchameleon.util.calendarlistformats.TWikiCalendarListFormat;
import net.numericalchameleon.util.calendarlistformats.DtcmListFormat;
import java.awt.ComponentOrientation;
import java.math.BigDecimal;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import jonelo.sugar.gui.GeneralGUI;
import net.numericalchameleon.categories.CategoryObject;
import net.numericalchameleon.gui.common.interfaces.DialogInterface;

public class ListGeneratorDialog extends javax.swing.JDialog {

    private final ListGeneratorCluster multipleNoticeCluster;
    private final ResourceBundle rb;

    public ListGeneratorDialog(DialogInterface parent, boolean modal, ListGeneratorCluster mnc) {
        super(parent.getFrame(), modal);
        this.rb = parent.getResourceBundle();
        this.multipleNoticeCluster = mnc;

        if (parent.getFrame().isUndecorated()) {
            setUndecorated(true);
            getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
        }

        initComponents();
        buttonGroup.add(oneTargetRadioButton);
        buttonGroup.add(multipleTargetsRadioButton);
        buttonGroup.add(allTargetsRadioButton);
        allTargetsRadioButton.setSelected(multipleNoticeCluster.getTargets() == ListGeneratorCluster.ALL_TARGETS);
        multipleTargetsRadioButton.setSelected(multipleNoticeCluster.getTargets() == ListGeneratorCluster.MULTIPLE_TARGETS);
        oneTargetRadioButton.setSelected(multipleNoticeCluster.getTargets() == ListGeneratorCluster.ALL_TARGETS);
        startTextField.setText(mnc.getStartValue().toString().replace('.', CategoryObject.getDecSep()));
        endTextField.setText(mnc.getEndValue().toString().replace('.', CategoryObject.getDecSep()));
        stepTextField.setText(mnc.getStepValue().toString().replace('.', CategoryObject.getDecSep()));

        if (!mnc.isListFormatVisible()) {
            listFormatPanel.setVisible(false);
            pack();
        }
        setLocationRelativeTo(parent.getFrame());
        ComponentOrientation ce = ComponentOrientation.getOrientation(Locale.getDefault());
        if (!ce.isLeftToRight()) {
            GeneralGUI.applyOrientation(listPanel, ce);
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        listPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        stepLabel = new javax.swing.JLabel();
        stepTextField = new javax.swing.JTextField();
        startTextField = new javax.swing.JTextField();
        endTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        oneTargetRadioButton = new javax.swing.JRadioButton();
        multipleTargetsRadioButton = new javax.swing.JRadioButton();
        allTargetsRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        listFormatPanel = new javax.swing.JPanel();
        listFormatComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setTitle(rb.getString("GUI.List.Title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        startLabel.setText(rb.getString("GUI.List.Start.Label")); // NOI18N

        endLabel.setText(rb.getString("GUI.List.End.Label")); // NOI18N

        stepLabel.setText(rb.getString("GUI.List.Step.Label")); // NOI18N

        startTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                startTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepLabel)
                    .addComponent(endLabel)
                    .addComponent(startLabel))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(startTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(endTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(endTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oneTargetRadioButton.setSelected(true);
        oneTargetRadioButton.setText(rb.getString("GUI.List.CalculateForOneTarget.Label")); // NOI18N
        oneTargetRadioButton.setToolTipText("all target units");
        oneTargetRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oneTargetRadioButtonItemStateChanged(evt);
            }
        });

        multipleTargetsRadioButton.setText(rb.getString("GUI.List.CalculateForMultipleTargets.Label")); // NOI18N
        multipleTargetsRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                multipleTargetsRadioButtonItemStateChanged(evt);
            }
        });

        allTargetsRadioButton.setText(rb.getString("GUI.List.CalculateForAllTargets.Label")); // NOI18N
        allTargetsRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                allTargetsRadioButtonItemStateChanged(evt);
            }
        });

        jLabel1.setText(rb.getString("GUI.List.CalculateFor.Label")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allTargetsRadioButton)
                    .addComponent(oneTargetRadioButton)
                    .addComponent(jLabel1)
                    .addComponent(multipleTargetsRadioButton))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneTargetRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multipleTargetsRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allTargetsRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listFormatPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "iCalendar (RFC 5545)", "dtcm (CDE)", "Outlook", "vCalendar", "xCal", "TWiki/Foswiki Calendar" }));

        jLabel2.setText(rb.getString("GUI.List.Format.Label")); // NOI18N

        javax.swing.GroupLayout listFormatPanelLayout = new javax.swing.GroupLayout(listFormatPanel);
        listFormatPanel.setLayout(listFormatPanelLayout);
        listFormatPanelLayout.setHorizontalGroup(
            listFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listFormatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(listFormatComboBox, 0, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        listFormatPanelLayout.setVerticalGroup(
            listFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listFormatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/numericalchameleon/resources/icons/pix16x16/close.png"))); // NOI18N
        cancelButton.setText(rb.getString("GUI.General.Cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/numericalchameleon/resources/icons/pix16x16/ok.png"))); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listFormatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listFormatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multipleTargetsRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_multipleTargetsRadioButtonItemStateChanged
        multipleNoticeCluster.setTargets(ListGeneratorCluster.MULTIPLE_TARGETS);
    }//GEN-LAST:event_multipleTargetsRadioButtonItemStateChanged

    private void startTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startTextFieldKeyReleased
        endTextField.setText(startTextField.getText());
    }//GEN-LAST:event_startTextFieldKeyReleased

    private void allTargetsRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_allTargetsRadioButtonItemStateChanged
        multipleNoticeCluster.setTargets(ListGeneratorCluster.ALL_TARGETS);
    }//GEN-LAST:event_allTargetsRadioButtonItemStateChanged

    private void oneTargetRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oneTargetRadioButtonItemStateChanged
        multipleNoticeCluster.setTargets(ListGeneratorCluster.ONE_TARGET);
    }//GEN-LAST:event_oneTargetRadioButtonItemStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        multipleNoticeCluster.setSuccess(false);
        closeDialog();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // check start, end and step value
        try {
            multipleNoticeCluster.setStartValue(new BigDecimal(startTextField.getText().trim().replace(CategoryObject.getDecSep(), '.')));
            multipleNoticeCluster.setEndValue(new BigDecimal(endTextField.getText().trim().replace(CategoryObject.getDecSep(), '.')));
            multipleNoticeCluster.setStepValue(new BigDecimal(stepTextField.getText().trim().replace(CategoryObject.getDecSep(), '.')));
            multipleNoticeCluster.setSuccess(true);
            if (multipleNoticeCluster.isListFormatVisible()) {
                if (listFormatComboBox.getSelectedItem().equals("dtcm (CDE)")) {
                    multipleNoticeCluster.setListFormat(new DtcmListFormat());
                } else if (listFormatComboBox.getSelectedItem().equals("Outlook")) {
                    multipleNoticeCluster.setListFormat(new OutlookListFormat());
                } else if (listFormatComboBox.getSelectedItem().equals("vCalendar")) {
                    multipleNoticeCluster.setListFormat(new VCalendarListFormat());
                } else if (listFormatComboBox.getSelectedItem().equals("iCalendar (RFC 5545)")) {
                    multipleNoticeCluster.setListFormat(new ICalendarListFormat());
                } else if (listFormatComboBox.getSelectedItem().equals("xCal")) {
                    multipleNoticeCluster.setListFormat(new XCalendarListFormat());
                } else if (listFormatComboBox.getSelectedItem().equals("TWiki/Foswiki Calendar")) {
                    multipleNoticeCluster.setListFormat(new TWikiCalendarListFormat());
                } else {
                    multipleNoticeCluster.setListFormat(null);
                }
            }
            closeDialog();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Number Format Error");
        }

    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        closeDialog();
    }//GEN-LAST:event_closeDialog

    private void closeDialog() {
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allTargetsRadioButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel endLabel;
    private javax.swing.JTextField endTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox listFormatComboBox;
    private javax.swing.JPanel listFormatPanel;
    private javax.swing.JPanel listPanel;
    private javax.swing.JRadioButton multipleTargetsRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton oneTargetRadioButton;
    private javax.swing.JLabel startLabel;
    private javax.swing.JTextField startTextField;
    private javax.swing.JLabel stepLabel;
    private javax.swing.JTextField stepTextField;
    // End of variables declaration//GEN-END:variables
}
